on:
  release:
    types: [published]
jobs:
  release_windows:
    runs-on: ubuntu-latest
    steps:
      - name: download Windows
        id: download-windows
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: the_ascension_of_the_lamb-windows.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Windows)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: the-ascension-of-the-lamb
          ITCH_USER: queenofsquiggles
          PACKAGE: the_ascension_of_the_lamb-windows.zip
          VERSION: ${{ steps.download-windows.outputs.version }}
  release_macos:
    runs-on: ubuntu-latest
    steps:
      - name: download MacOS
        id: download-macos
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: the_ascension_of_the_lamb-mac.zip
          token: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (MacOS)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac
          ITCH_GAME: the-ascension-of-the-lamb
          ITCH_USER: queenofsquiggles
          PACKAGE: the_ascension_of_the_lamb-mac.zip
          VERSION: ${{ steps.download-macos.outputs.version }}
  release_linux:
    runs-on: ubuntu-latest
    steps:
      - name: download Linux
        id: download-linux
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: the_ascension_of_the_lamb-linux.zip
          token: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Linux)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: the-ascension-of-the-lamb
          ITCH_USER: queenofsquiggles
          PACKAGE: the_ascension_of_the_lamb-linux.zip
          VERSION: ${{ steps.download-linux.outputs.version }}
